version: '3.4'

services:



 app-infrastructure-pgsql-test:
    container_name: app-infrastructure-pgsql-test
    image: postgres:10.5
    volumes:
      - "/var/test/icxl/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${PostgresDB_User}
      - POSTGRES_PASSWORD=${PostgresDB_Password}
    ports:
      - "8501:5432"
    networks:
      - test
    restart: always

 app-infrastructure-consul-test:
    container_name: app-infrastructure-consul-test
    image: consul:1.4.4
    command: agent -dev -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - test
    restart: always


networks:
  test: