# version: '3.4'

# services:
# # MoreJee Database
  # app-infrastructure-pgsql:
    # container_name: app-infrastructure-pgsql-${ContainerSuffix}
    # image: postgres:10.5
    # volumes:
      # - "/var/bamboo/dmzpostgresdb/data:/var/lib/postgresql/data"
    # environment:
      # - POSTGRES_USER=${PostgresDB_User}
      # - POSTGRES_PASSWORD=${PostgresDB_Password}
    # ports:
      # - "${ApplicationStartPortPrefix}01:5432"
    # networks:
      # - icxlnetwork
    # restart: always
# # 1.2 Consul
  # app-infrastructure-consul:
    # container_name: app-infrastructure-consul-${ContainerSuffix}
    # image: consul:1.4.4
    # command: agent -dev -client=0.0.0.0 -bind=0.0.0.0
    # ports:
      # - "${ApplicationStartPortPrefix}02:8500"
    # networks:
      # - icxlnetwork
    # restart: always
# # 1.3 APIGateway
  # app-infrastructure-apigateway:
    # container_name: app-infrastructure-apigateway-${ContainerSuffix}
    # image: ${DockerHub_Registry}/icxl-apigateway:${DockerImage_Tag}
    # ports:
      # - "${ApplicationStartPortPrefix}03:80"
    # volumes:
      # - "/var/${VolumeBaseDirectory}/app-infrastructure-apigateway/logs:/app/logs"
    # environment:
      # - ASPNETCORE_ENVIRONMENT=Release
    # networks:
      # - icxlnetwork
    # depends_on:
      # - app-infrastructure-pgsql
      # - app-infrastructure-consul
    # restart: always
     # #idsServer
  # app-infrastructure-idsServer:
    # container_name: app-infrastructure-idsServer-${ContainerSuffix}
    # image: ${DockerHub_Registry}/icxl-ids:${DockerImage_Tag}
    # environment:
      # - ConnectionString=Server=app-infrastructure-pgsql;Port=5432;Database=${BasicServerDB};User Id=${PostgresDB_User};Password=${PostgresDB_Password}
      # # Consul
      # - ConsulConfig:Server:IP=app-infrastructure-consul
      # - ConsulConfig:Server:Port=8500
      # - ConsulConfig:Client:IP=app-infrastructure-idsServer
      # - ConsulConfig:Client:Port=80
    # ports:
      # - "5000:80"
    # networks:
      # - icxlnetwork
    # restart: always

# networks:
  # icxlnetwork:
    # external: true



version: '3.4'

services:
# MoreJee Database
  app-infrastructure-pgsql:
    container_name: app-infrastructure-pgsql-icxl
    image: postgres:10.5
    volumes:
      - "/var/bamboo/dmzpostgresdb/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "9501:5432"
    networks:
      - icxlnetwork
    restart: always
# 1.2 Consul
  app-infrastructure-consul:
    container_name: app-infrastructure-consul-icxl
    image: consul:1.4.4
    command: agent -dev -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - "9502:8500"
    networks:
      - icxlnetwork
    restart: always
# 1.3 APIGateway
  app-infrastructure-apigateway:
    container_name: app-infrastructure-apigateway-icxl
    image: registry.cn-shanghai.aliyuncs.com/icxl-core/icxl-apigateway:0909
    ports:
      - "9503:80"
    volumes:
      - "/var/${VolumeBaseDirectory}/app-infrastructure-apigateway/logs:/app/logs"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    networks:
      - icxlnetwork
    depends_on:
      - app-infrastructure-pgsql
      - app-infrastructure-consul
    restart: always
     #idsServer
  app-infrastructure-idsServer:
    container_name: app-infrastructure-idsServer-icxl
    image: registry.cn-shanghai.aliyuncs.com/icxl-core/icxl-ids:0909
    environment:
      - ConnectionString=Server=app-infrastructure-pgsql;Port=5432;Database=appbasic;User Id=postgres;Password=root
      # Consul
      - ConsulConfig:Server:IP=app-infrastructure-consul
      - ConsulConfig:Server:Port=8500
      - ConsulConfig:Client:IP=app-infrastructure-idsServer
      - ConsulConfig:Client:Port=80
    ports:
      - "5000:80"
    networks:
      - icxlnetwork
    restart: always

networks:
  icxlnetwork:
    external: true